with Templates_Parser;
with Translate_Utils;
with Web_Utils;
with EU.Web.Settings;
with EU_Types.Web_IO;
with BE_Types.Web_IO;
with Text_Utils;

package body EU.BE.Household.Web_IO is

    use EU.BE.I81N.Translations;
    use EU_Types.Web_IO;
    use BE_Types.Web_IO;
    use Text_Utils;
    
   function To_HTML( hh : in Household_Rec; lang : Languages ) return String is
      use Templates_Parser;
      translations : Translate_Set;
   begin
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-NUMBER-OF-ROOMS-VALUE", Web_Format( hh.assets_main_residence_number_of_rooms, lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-NUMBER-OF-ROOMS-STR", Lookup( "assets_main_residence_number_of_rooms", lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-TENURE-VALUE", Web_Format( hh.assets_main_residence_tenure, lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-TENURE-STR", Lookup( "assets_main_residence_tenure", lang )));
      -- Insert( translations, Templates_Parser.Assoc( "ASSETS-FINANCIAL-CAPITAL-VALUE", Web_Format( hh.assets_financial_capital, lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-FINANCIAL-CAPITAL-STR", Lookup( "assets_financial_capital", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-VALUE", Web_Format( hh.expenditure_housing_cost, lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-STR", Lookup( "expenditure_housing_cost", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-RENT-VALUE", Web_Format( hh.expenditure_housing_cost_rent, lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-RENT-STR", Lookup( "expenditure_housing_cost_rent", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-MORTGAGE-PAYMENT-INTEREST-AND-CAPITAL-MORTGAGE-INTEREST-VALUE", Web_Format( hh.expenditure_housing_cost_mortgage_payment_interest_and_capital_mortgage_interest, lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-MORTGAGE-PAYMENT-INTEREST-AND-CAPITAL-MORTGAGE-INTEREST-STR", Lookup( "expenditure_housing_cost_mortgage_payment_interest_and_capital_mortgage_interest", lang )));
      -- derived
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-QUINTILE-VALUE", Web_Format( hh.equivalent_income_quintile, lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-DECILE-VALUE", Web_Format( hh.equivalent_income_decile, lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-NET-INCOME-VALUE", Web_Format( hh.equivalent_income, lang ))); 
      
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-QUINTILE-STR", Lookup( "equivalent_income_quintile", lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-DECILE-STR", Lookup( "equivalent_income_decile", lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-NET-INCOME-STR", Lookup( "personal_equivalent_income", lang ))); 

      Insert( translations, Assoc( "ASSETS", Lookup( "Assets", lang )));
      Insert( translations, Assoc( "EXPENDITURES", Lookup( "Expenditures", lang )));
      
      return Web_Utils.Parse_Template( 
         EU.Web.Settings.template_components_path & EU.Web.Settings.dir_separator & "household", 
         translations );      
   end To_HTML;
  
   function To_HTML( pers : in Person_Rec; lang : Languages ) return String is
      use Templates_Parser;
      translations : Translate_Set;
   begin

      -- ==== AUTOGENERATED STARTS
      
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-HOUSEHOLD-VALUE", Web_Format( pers.identifier_household, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-HOUSEHOLD-STR", Lookup( "identifier_household", lang )));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-PERSON-VALUE", Web_Format( pers.identifier_person, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-PERSON-STR", Lookup( "identifier_person", lang )));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-FATHER-VALUE", Web_Format( pers.identifier_father, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-FATHER-STR", Lookup( "identifier_father", lang )));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-MOTHER-VALUE", Web_Format( pers.identifier_mother, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-MOTHER-STR", Lookup( "identifier_mother", lang )));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-PARTNER-VALUE", Web_Format( pers.identifier_partner, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IDENTIFIER-PARTNER-STR", Lookup( "identifier_partner", lang )));
      -- Insert( translations, Templates_Parser.Assoc( "ORIGINAL-HOUSEHOLD-ID-VALUE", Web_Format( pers.original_household_id, lang )  ));
      -- Insert( translations, Templates_Parser.Assoc( "ORIGINAL-HOUSEHOLD-ID-STR", Lookup( "original_household_id", lang )));
      -- Insert( translations, Templates_Parser.Assoc( "ORIGINAL-PERSON-ID-VALUE", Web_Format( pers.original_person_id, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "ORIGINAL-PERSON-ID-STR", Lookup( "original_person_id", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-AGE-VALUE", Web_Format( pers.demographic_age, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-AGE-STR", Lookup( "demographic_age", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-GENDER-VALUE", Web_Format( pers.demographic_gender, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-GENDER-STR", Lookup( "demographic_gender", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-MARITAL-STATUS-VALUE", Web_Format( pers.demographic_marital_status, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-MARITAL-STATUS-STR", Lookup( "demographic_marital_status", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-CITIZENSHIP-VALUE", Web_Format( pers.demographic_citizenship, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-CITIZENSHIP-STR", Lookup( "demographic_citizenship", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-DISABILITY-VALUE", Web_Format( pers.demographic_disability, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-DISABILITY-STR", Lookup( "demographic_disability", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-DATE-OF-INTERVIEW-VALUE", Web_Format( pers.demographic_date_of_interview, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-DATE-OF-INTERVIEW-STR", Lookup( "demographic_date_of_interview", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-WEIGHT-VALUE", Web_Format( pers.demographic_weight, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-WEIGHT-STR", Lookup( "demographic_weight", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-MAIN-OR-BASIC-VALUE", Web_Format( pers.demographic_sample_units_main_or_basic, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-MAIN-OR-BASIC-STR", Lookup( "demographic_sample_units_main_or_basic", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-01-VALUE", Web_Format( pers.demographic_sample_units_01, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-01-STR", Lookup( "demographic_sample_units_01", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-02-VALUE", Web_Format( pers.demographic_sample_units_02, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-SAMPLE-UNITS-02-STR", Lookup( "demographic_sample_units_02", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-COUNTRY-VALUE", Web_Format( pers.demographic_country, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-COUNTRY-STR", Lookup( "demographic_country", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-CURRENT-STATUS-VALUE", Web_Format( pers.demographic_education_current_status, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-CURRENT-STATUS-STR", Lookup( "demographic_education_current_status", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-HIGHEST-STATUS-VALUE", Web_Format( pers.demographic_education_highest_status, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-HIGHEST-STATUS-STR", Lookup( "demographic_education_highest_status", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-NUMBER-OF-YEARS-VALUE", Web_Format( pers.demographic_education_number_of_years, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-NUMBER-OF-YEARS-STR", Lookup( "demographic_education_number_of_years", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-WHEN-ACHIEVED-HIGHEST-STATUS-VALUE", Web_Format( pers.demographic_education_when_achieved_highest_status, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-EDUCATION-WHEN-ACHIEVED-HIGHEST-STATUS-STR", Lookup( "demographic_education_when_achieved_highest_status", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-REGION-NUTS-LEVEL-1-VALUE", Web_Format( pers.demographic_region_nuts_level_1, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-REGION-NUTS-LEVEL-1-STR", Lookup( "demographic_region_nuts_level_1", lang )));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-CONSENSUAL-UNION-VALUE", Web_Format( pers.demographic_consensual_union, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "DEMOGRAPHIC-CONSENSUAL-UNION-STR", Lookup( "demographic_consensual_union", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-ECONOMIC-STATUS-VALUE", Web_Format( pers.labour_market_economic_status, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-ECONOMIC-STATUS-STR", Lookup( "labour_market_economic_status", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-CIVIL-SERVANT-VALUE", Web_Format( pers.labour_market_civil_servant, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-CIVIL-SERVANT-STR", Lookup( "labour_market_civil_servant", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-FIRM-SIZE-VALUE", Web_Format( pers.labour_market_firm_size, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-FIRM-SIZE-STR", Lookup( "labour_market_firm_size", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-INDUSTRY-NACE-VALUE", Web_Format( pers.labour_market_industry_nace, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-INDUSTRY-NACE-STR", Lookup( "labour_market_industry_nace", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-INDUSTRY-NACE-DETAILED-INDUSTRY-VALUE", Web_Format( pers.labour_market_industry_nace_detailed_industry, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-INDUSTRY-NACE-DETAILED-INDUSTRY-STR", Lookup( "labour_market_industry_nace_detailed_industry", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-IN-WORK-MONTHS-PER-YEAR-VALUE", Web_Format( pers.labour_market_in_work_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-IN-WORK-MONTHS-PER-YEAR-STR", Lookup( "labour_market_in_work_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-HOURS-WORKED-PER-WEEK-VALUE", Web_Format( pers.labour_market_hours_worked_per_week, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-HOURS-WORKED-PER-WEEK-STR", Lookup( "labour_market_hours_worked_per_week", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-IN-WORK-WORK-HISTORY-LENGTH-OF-TIME-IN-MONTHS-VALUE", Web_Format( pers.labour_market_in_work_work_history_length_of_time_in_months, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-IN-WORK-WORK-HISTORY-LENGTH-OF-TIME-IN-MONTHS-STR", Lookup( "labour_market_in_work_work_history_length_of_time_in_months", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-OCCUPATION-ISCO-1-DIGIT-VALUE", Web_Format( pers.labour_market_occupation_isco_1_digit, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-OCCUPATION-ISCO-1-DIGIT-STR", Lookup( "labour_market_occupation_isco_1_digit", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-PENSIONER-MONTHS-PER-YEAR-VALUE", Web_Format( pers.labour_market_pensioner_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-PENSIONER-MONTHS-PER-YEAR-STR", Lookup( "labour_market_pensioner_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-SELF-EMPLOYED-VALUE", Web_Format( pers.labour_market_self_employed, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-SELF-EMPLOYED-STR", Lookup( "labour_market_self_employed", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-UNEMPLOYED-MONTHS-PER-YEAR-VALUE", Web_Format( pers.labour_market_unemployed_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-UNEMPLOYED-MONTHS-PER-YEAR-STR", Lookup( "labour_market_unemployed_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-OUT-OF-WORK-ACTIVELY-SEEKING-VALUE", Web_Format( pers.labour_market_out_of_work_actively_seeking, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "LABOUR-MARKET-OUT-OF-WORK-ACTIVELY-SEEKING-STR", Lookup( "labour_market_out_of_work_actively_seeking", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-IMPUTED-VALUE-WAGE-OR-SALARY-VALUE", Web_Format( pers.income_imputed_value_wage_or_salary, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-IMPUTED-VALUE-WAGE-OR-SALARY-STR", Lookup( "income_imputed_value_wage_or_salary", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-EMPLOYMENT-VALUE", Web_Format( pers.income_employment, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-EMPLOYMENT-STR", Lookup( "income_employment", lang )));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-FRINGE-BENEFIT-VALUE", Web_Format( pers.in_kind_fringe_benefit, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-FRINGE-BENEFIT-STR", Lookup( "in_kind_fringe_benefit", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PRIVATE-PENSION-VALUE", Web_Format( pers.income_private_pension, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PRIVATE-PENSION-STR", Lookup( "income_private_pension", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-SELF-EMPLOYMENT-VALUE", Web_Format( pers.income_self_employment, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-SELF-EMPLOYMENT-STR", Lookup( "income_self_employment", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EDUCATION-VALUE", Web_Format( pers.benefit_education, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EDUCATION-STR", Lookup( "benefit_education", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-UNEMPLOYMENT-VALUE", Web_Format( pers.benefit_unemployment, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-UNEMPLOYMENT-STR", Lookup( "benefit_unemployment", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-HEALTH-VALUE", Web_Format( pers.pension_health, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-HEALTH-STR", Lookup( "pension_health", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-DISABILITY-VALUE", Web_Format( pers.pension_disability, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-DISABILITY-STR", Lookup( "pension_disability", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-OLD-AGE-VALUE", Web_Format( pers.pension_old_age, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-OLD-AGE-STR", Lookup( "pension_old_age", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-SURVIVORS-VALUE", Web_Format( pers.pension_survivors, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-SURVIVORS-STR", Lookup( "pension_survivors", lang )));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-IMPUTED-VALUE-HOUSING-VALUE", Web_Format( pers.in_kind_imputed_value_housing, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-IMPUTED-VALUE-HOUSING-STR", Lookup( "in_kind_imputed_value_housing", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-INVESTMENT-VALUE", Web_Format( pers.income_investment, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-INVESTMENT-STR", Lookup( "income_investment", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PROPERTY-RENT-VALUE", Web_Format( pers.income_property_rent, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PROPERTY-RENT-STR", Lookup( "income_property_rent", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PROPERTY-VALUE", Web_Format( pers.income_property, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PROPERTY-STR", Lookup( "income_property", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PRIVATE-TRANSFERS-VALUE", Web_Format( pers.income_private_transfers, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-PRIVATE-TRANSFERS-STR", Lookup( "income_private_transfers", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-SOCIAL-ASSISTANCE-VALUE", Web_Format( pers.benefit_social_assistance, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-SOCIAL-ASSISTANCE-STR", Lookup( "benefit_social_assistance", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-HOUSING-VALUE", Web_Format( pers.benefit_housing, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-HOUSING-STR", Lookup( "benefit_housing", lang )));
      Insert( translations, Templates_Parser.Assoc( "TAX-PROPERTY-TAX-VALUE", Web_Format( pers.tax_property_tax, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "TAX-PROPERTY-TAX-STR", Lookup( "tax_property_tax", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-OTHER-VALUE", Web_Format( pers.income_other, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-OTHER-STR", Lookup( "income_other", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-DISPOSABLE-VALUE", Web_Format( pers.income_disposable, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-DISPOSABLE-STR", Lookup( "income_disposable", lang )));
      Insert( translations, Templates_Parser.Assoc( "TAX-REPAYMENTS-OR-RECEIPTS-VALUE", Web_Format( pers.tax_repayments_or_receipts, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "TAX-REPAYMENTS-OR-RECEIPTS-STR", Lookup( "tax_repayments_or_receipts", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-MAIN-OR-BASIC-VALUE", Web_Format( pers.benefit_child_main_or_basic, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-MAIN-OR-BASIC-STR", Lookup( "benefit_child_main_or_basic", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-BIRTH-OR-ADOPTION-VALUE", Web_Format( pers.benefit_child_birth_or_adoption, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-BIRTH-OR-ADOPTION-STR", Lookup( "benefit_child_birth_or_adoption", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-VALUE", Web_Format( pers.benefit_child, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-CHILD-STR", Lookup( "benefit_child", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-MATERNITY-VALUE", Web_Format( pers.benefit_maternity, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-MATERNITY-STR", Lookup( "benefit_maternity", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-FAMILY-PARENTAL-LEAVE-VALUE", Web_Format( pers.benefit_family_parental_leave, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-FAMILY-PARENTAL-LEAVE-STR", Lookup( "benefit_family_parental_leave", lang )));
      -- Insert( translations, Templates_Parser.Assoc( "BENEFIT-FAMILY-VALUE", Web_Format( pers.benefit_family, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-FAMILY-STR", Lookup( "benefit_family", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-EMPLOYMENT-MONTHS-PER-YEAR-VALUE", Web_Format( pers.income_employment_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-EMPLOYMENT-MONTHS-PER-YEAR-STR", Lookup( "income_employment_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-FRINGE-BENEFIT-MONTHS-PER-YEAR-VALUE", Web_Format( pers.in_kind_fringe_benefit_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "IN-KIND-FRINGE-BENEFIT-MONTHS-PER-YEAR-STR", Lookup( "in_kind_fringe_benefit_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "INCOME-SELF-EMPLOYMENT-MONTHS-PER-YEAR-VALUE", Web_Format( pers.income_self_employment_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "INCOME-SELF-EMPLOYMENT-MONTHS-PER-YEAR-STR", Lookup( "income_self_employment_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-UNEMPLOYMENT-MONTHS-PER-YEAR-VALUE", Web_Format( pers.benefit_unemployment_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-UNEMPLOYMENT-MONTHS-PER-YEAR-STR", Lookup( "benefit_unemployment_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-DISABILITY-MONTHS-PER-YEAR-VALUE", Web_Format( pers.pension_disability_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-DISABILITY-MONTHS-PER-YEAR-STR", Lookup( "pension_disability_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-HEALTH-MONTHS-PER-YEAR-VALUE", Web_Format( pers.pension_health_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-HEALTH-MONTHS-PER-YEAR-STR", Lookup( "pension_health_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-OLD-AGE-MONTHS-PER-YEAR-VALUE", Web_Format( pers.pension_old_age_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-OLD-AGE-MONTHS-PER-YEAR-STR", Lookup( "pension_old_age_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "PENSION-SURVIVORS-MONTHS-PER-YEAR-VALUE", Web_Format( pers.pension_survivors_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "PENSION-SURVIVORS-MONTHS-PER-YEAR-STR", Lookup( "pension_survivors_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "TAX-INCOME-TAX-AND-SICS-VALUE", Web_Format( pers.tax_income_tax_and_sics, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "TAX-INCOME-TAX-AND-SICS-STR", Lookup( "tax_income_tax_and_sics", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EARLY-RETIREMENT-VALUE", Web_Format( pers.benefit_early_retirement, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EARLY-RETIREMENT-STR", Lookup( "benefit_early_retirement", lang )));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EARLY-RETIREMENT-EARLY-RETIREMENT-PENSION-MONTHS-PER-YEAR-VALUE", Web_Format( pers.benefit_early_retirement_early_retirement_pension_months_per_year, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "BENEFIT-EARLY-RETIREMENT-EARLY-RETIREMENT-PENSION-MONTHS-PER-YEAR-STR", Lookup( "benefit_early_retirement_early_retirement_pension_months_per_year", lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-NUMBER-OF-ROOMS-VALUE", Web_Format( pers.assets_main_residence_number_of_rooms, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-NUMBER-OF-ROOMS-STR", Lookup( "assets_main_residence_number_of_rooms", lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-TENURE-VALUE", Web_Format( pers.assets_main_residence_tenure, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-MAIN-RESIDENCE-TENURE-STR", Lookup( "assets_main_residence_tenure", lang )));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-FINANCIAL-CAPITAL-VALUE", Web_Format( pers.assets_financial_capital, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "ASSETS-FINANCIAL-CAPITAL-STR", Lookup( "assets_financial_capital", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-MAINTENANCE-PAYMENT-VALUE", Web_Format( pers.expenditure_maintenance_payment, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-MAINTENANCE-PAYMENT-STR", Lookup( "expenditure_maintenance_payment", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-PRIVATE-PENSION-VOLUNTARY-VALUE", Web_Format( pers.expenditure_private_pension_voluntary, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-PRIVATE-PENSION-VOLUNTARY-STR", Lookup( "expenditure_private_pension_voluntary", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-VALUE", Web_Format( pers.expenditure_housing_cost, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-STR", Lookup( "expenditure_housing_cost", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-RENT-VALUE", Web_Format( pers.expenditure_housing_cost_rent, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-RENT-STR", Lookup( "expenditure_housing_cost_rent", lang )));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-MORTGAGE-PAYMENT-INTEREST-AND-CAPITAL-MORTGAGE-INTEREST-VALUE", Web_Format( pers.expenditure_housing_cost_mortgage_payment_interest_and_capital_mortgage_interest, lang )  ));
      Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-MORTGAGE-PAYMENT-INTEREST-AND-CAPITAL-MORTGAGE-INTEREST-STR", Lookup( "expenditure_housing_cost_mortgage_payment_interest_and_capital_mortgage_interest", lang )));
      -- Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-OTHER-VALUE", Web_Format( pers.expenditure_housing_cost_other, lang )  ));
      -- Insert( translations, Templates_Parser.Assoc( "EXPENDITURE-HOUSING-COST-OTHER-STR", Lookup( "expenditure_housing_cost_other", lang )));      
      -- == AUTOGENERATED ENDS      
            --
      -- created variables
      -- FIXME these are not mappped fully, or translated
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-QUINTILE-VALUE", Web_Format( pers.equivalent_income_quintile, lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-DECILE-VALUE", Web_Format( pers.equivalent_income_decile, lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-NET-INCOME-VALUE", Web_Format( pers.equivalent_income, lang ))); 
      
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-QUINTILE-STR", Lookup( "equivalent_income_quintile", lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-INCOME-DECILE-STR", Lookup( "equivalent_income_decile", lang ))); 
      Insert( translations, Templates_Parser.Assoc( "EQUIVALENT-NET-INCOME-STR", Lookup( "personal_equivalent_income", lang ))); 
      Insert( translations, Templates_Parser.Assoc( "DERIVED-VARIABLES",  Lookup( "derived_variables", lang ))); 
      
      return Web_Utils.Parse_Template( 
         EU.Web.Settings.template_components_path & 
         EU.Web.Settings.dir_separator & "personal", 
         translations );      
   end To_HTML;
   
end EU.BE.Household.Web_IO;
